name = "NaiveNASlib"
uuid = "bd45eb3e-47ce-54bd-9eaf-e86c5f900853"
version = "1.1.1"

[deps]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Cbc = "0.6, 0.7"
JuMP = "0.21"
LightGraphs = "1.2.0"
MetaGraphs = "0.6.4"
julia = "1"

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "InteractiveUtils"]
